# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eab28bfbe2bf754cdb3b891ebe6779719eb41530425c70e6b3b44be7b60e9a624635ca4c73f9477af83d3c26948c6e7f768ad2c5ae85d6acb18ae435319193c

test:
  secret_key_base: 1aaf1b3b3bff228752e338daa960517a2abec1ed68d72aac23a87ae0eacebf32c87608a3cace3864594d0b66058620686147ff7372df937b07c6a74228e65332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
